Interface
team5419/fault pull request #9
Opened 2019-12-09 18:41 UTC by nicholasunderwood

Unit and math libs

2019-12-10 15:47 UTC, FelixMo42 commented on .pre-commit-config.yaml
> +-   repo: https://github.com/team5499/pre-commit-hooks
Shouldn't this be team 5419?

2019-12-11 00:33 UTC, andycate requested changes
Fix some stuff

2019-12-11 00:33 UTC, andycate commented on .pre-commit-config.yaml
> +    rev: v0.3.2
????

2019-12-11 00:33 UTC, andycate commented on .travis.yml
> +  - secure: H4xBumrS4Z8OXqW+evg/iczS0kRaK7g/HAn7g+a4bwxfHYME6CN7hvwy9MY+McidDcXz/BD88eJnZ4/SyKUdlFFd5PqN5tiUGkHsY9QcQjRTw5alNgONk8S5vHDXqlRizF5EKUm7yBC4DRgFlmhF4TJybxwjI3dSFrKYakvEEtlCC6O3JuXq/PYdoz9
We need to fix this

2019-12-11 00:33 UTC, andycate commented on README.md
> +
BRuH

2019-12-11 00:33 UTC, andycate commented on build.gradle
> +    id "edu.wpi.first.GradleRIO" version "2019.3.2"
Noyan, use the right version

2019-12-11 00:33 UTC, andycate commented on build.gradle
> +version = '3.0.0-SNAPSHOT'
make sure to change this before merging

2019-12-11 00:33 UTC, andycate commented on build.gradle
> +                name = 'Fault'
change back

2019-12-11 00:41 UTC, FelixMo42 reviewed
Have we done any benchmarking on if the SI unit system slows things down? It seems like that could be a real drag if it has to be constantly creating and destroying objects, but it might have some sort of internal optimization I don't know about.

2019-12-11 00:41 UTC, FelixMo42 commented on build.gradle
> +    id "edu.wpi.first.GradleRIO" version "2019.3.2"
Why are we reverting to an older version?

2019-12-11 00:41 UTC, FelixMo42 commented on src/main/kotlin/org/team5419/fault/auto/ActionGroup.kt
> +open class SerialAction(actions: MutableList<Action>) : ActionGroup() {
Why is this a mutable list, that seems like a recipe for bugs?

2019-12-11 00:41 UTC, FelixMo42 commented on .pre-commit-config.yaml
> +-   repo: https://github.com/team5499/pre-commit-hooks
Shouldn't this be team 5419?

2019-12-11 00:41 UTC, FelixMo42 commented on src/main/kotlin/org/team5419/fault/auto/ActionUtil.kt
> +    private val actions = mutableListOf<Action>()
Again, don't use mutable list if you don't have to.

2019-12-11 00:41 UTC, FelixMo42 commented on src/main/kotlin/org/team5419/fault/hardware/AbstractBerkeliumEncoder.kt
> +    override val velocity: SIUnit<Velocity<T>> get() = model.fromNativeUnitVelocity(rawVelocity)
Shouldn't the interface include a way to zero the encoder?

2019-12-11 00:41 UTC, FelixMo42 commented on src/main/kotlin/org/team5419/fault/hardware/AbstractBerkeliumMotor.kt
> +}
We use a lot more functionality in the BerkeliumMotor class than just the follow function. It should be here

2019-12-11 00:41 UTC, FelixMo42 commented on src/main/kotlin/org/team5419/fault/math/geometry/Rotation2d.kt
> +import org.team5419.fault.math.units.derived.*
Isn't doing mass imports considered bad practice? I know are best friend Tox doesn't like it.

2019-12-11 00:41 UTC, FelixMo42 commented on src/main/kotlin/org/team5419/fault/math/geometry/Vector2.kt
> +import org.team5419.fault.math.units.*
Again, do we want to do mass imports?

2019-12-11 00:41 UTC, FelixMo42 commented on src/main/kotlin/org/team5419/fault/subsystems/Subsystem.kt
> +object SubsystemManager {
Do we need a way to get subsystems? Are we just going to pass all of them around manually? How is this going to work?

2019-12-11 00:41 UTC, FelixMo42 commented on src/main/kotlin/org/team5419/fault/util/Source.kt
> +typealias Source<T> = () -> T
What is this, the name doesn't say anything. This file need a bare minimum of docs.

2019-12-11 01:34 UTC, nicholasunderwood commented on src/main/kotlin/org/team5419/fault/auto/ActionGroup.kt
> +open class SerialAction(actions: MutableList<Action>) : ActionGroup() {
I would have thought that would only cause problems with multiple threads

2019-12-11 01:39 UTC, FelixMo42 commented on src/main/kotlin/org/team5419/fault/auto/ActionGroup.kt
> +open class SerialAction(actions: MutableList<Action>) : ActionGroup() {
Actions are run sorta sudo multithreaded. We do one tick per loop, but that means that somewhere else in the update loop someone could still change the list.

Also, we are multithreading some stuff.

2019-12-30 05:04 UTC, closed without merging